# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5b0ea625b310afee347ab187fe8c2c6650ad96a13df283f0c0dd4e7bab32a18e11163daf3dda5f0ea85361d113f95f77e9342084ddc8d43267f42beb533a5044

test:
  secret_key_base: f038ea67ca04c5bb6204ec6bda65d15ba8945259c2922444719f51799b89754db05fd94bd2a06cead158f7ab6002240b7f693efbedf7edd44f493a1b6cb78b31

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
